# Generated by Django 4.2.2 on 2023-06-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Areagestiondeconocimiento",
            fields=[
                (
                    "idareagestiondeconocimiento",
                    models.IntegerField(
                        db_column="idAreaGestionDeConocimiento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("fechadecreacion", models.DateField(db_column="fechaDeCreacion")),
            ],
            options={
                "db_table": "areagestiondeconocimiento",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Boletinsiun",
            fields=[
                (
                    "idboletinsiun",
                    models.IntegerField(
                        db_column="idBoletinSIUN", primary_key=True, serialize=False
                    ),
                ),
                ("fechalanzamiento", models.DateField(db_column="fechaLanzamiento")),
            ],
            options={
                "db_table": "boletinsiun",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comite",
            fields=[
                (
                    "idcomite",
                    models.IntegerField(
                        db_column="idComite", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.CharField(max_length=60)),
                (
                    "numerodeintegrantes",
                    models.IntegerField(db_column="numeroDeIntegrantes"),
                ),
            ],
            options={
                "db_table": "comite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "idconvocatoria",
                    models.IntegerField(
                        db_column="idConvocatoria", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fechadeinicio", models.DateField(db_column="fechaDeInicio")),
                ("fechalimite", models.DateField(db_column="fechaLimite")),
                ("cupos", models.IntegerField()),
                ("requisitos", models.TextField()),
                ("tipo", models.CharField(max_length=20)),
                ("descripcion", models.TextField()),
                ("presupuesto", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "convocatoria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "idfacultad",
                    models.IntegerField(
                        db_column="idFacultad", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                (
                    "numerodeestudiantes",
                    models.IntegerField(db_column="numeroDeEstudiantes"),
                ),
                ("numerodedocentes", models.IntegerField(db_column="numeroDeDocentes")),
                ("presupuestoneto", models.IntegerField(db_column="presupuestoNeto")),
            ],
            options={
                "db_table": "facultad",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupoinvestigacion",
            fields=[
                (
                    "idgrupoinvestigacion",
                    models.IntegerField(
                        db_column="idGrupoInvestigacion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "numerodeintegrantes",
                    models.IntegerField(db_column="numeroDeIntegrantes"),
                ),
                ("fechadecreacion", models.DateField(db_column="fechaDeCreacion")),
                ("tema", models.CharField(max_length=45)),
                (
                    "numerodepublicaciones",
                    models.SmallIntegerField(
                        blank=True, db_column="numeroDePublicaciones", null=True
                    ),
                ),
                ("categoria", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "grupoinvestigacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Infraestructura",
            fields=[
                (
                    "idinfraestructura",
                    models.IntegerField(
                        db_column="idInfraestructura", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                ("tipo", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "infraestructura",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Instituto",
            fields=[
                (
                    "idinstituto",
                    models.IntegerField(
                        db_column="idInstituto", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("fechadecreacion", models.DateField(db_column="fechaDeCreacion")),
                ("numerodegrupos", models.IntegerField(db_column="numeroDeGrupos")),
            ],
            options={
                "db_table": "instituto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Integrantevicerrectoria",
            fields=[
                (
                    "idintegrantevicerrectoria",
                    models.AutoField(
                        db_column="idIntegranteVicerrectoria",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fechadeingreso",
                    models.CharField(db_column="fechaDeIngreso", max_length=45),
                ),
                ("rol", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "integrantevicerrectoria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "idpersona",
                    models.IntegerField(
                        db_column="idPersona", primary_key=True, serialize=False
                    ),
                ),
                ("clave", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=45)),
                ("apellido", models.CharField(max_length=45)),
                (
                    "nivelacademico",
                    models.CharField(db_column="nivelAcademico", max_length=45),
                ),
                ("edad", models.IntegerField()),
                ("rol", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "persona",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "idproducto",
                    models.IntegerField(
                        db_column="idProducto", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                ("categoria", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Propuesta",
            fields=[
                (
                    "idpropuesta",
                    models.IntegerField(
                        db_column="idPropuesta", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=60)),
                ("descripcion", models.TextField()),
                (
                    "fechadecreacion",
                    models.DateField(
                        blank=True, db_column="fechaDeCreacion", null=True
                    ),
                ),
            ],
            options={
                "db_table": "propuesta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "idproyecto",
                    models.IntegerField(
                        db_column="idProyecto", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("enfasis", models.CharField(max_length=45)),
                ("fechadecreacion", models.DateField(db_column="fechaDeCreacion")),
            ],
            options={
                "db_table": "proyecto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "idpublicacion",
                    models.IntegerField(
                        db_column="idPublicacion", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("tema", models.CharField(max_length=45)),
                ("tipo", models.CharField(max_length=45)),
                ("fechadecreacion", models.DateField(db_column="fechaDeCreacion")),
            ],
            options={
                "db_table": "publicacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "idsede",
                    models.AutoField(
                        db_column="idSede", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("capacidad", models.IntegerField()),
                (
                    "numerodeestudiantes",
                    models.IntegerField(db_column="numeroDeEstudiantes"),
                ),
                ("numerodedocentes", models.IntegerField(db_column="numeroDeDocentes")),
                (
                    "fechadecreacion",
                    models.DateField(
                        blank=True, db_column="fechaDeCreacion", null=True
                    ),
                ),
            ],
            options={
                "db_table": "sede",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vicerrectoriainvestigacion",
            fields=[
                (
                    "idvicerrectoriainvestigacion",
                    models.AutoField(
                        db_column="idVicerrectoriaInvestigacion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("correo", models.CharField(max_length=30)),
                ("telefono", models.CharField(max_length=30)),
                ("presupuestofondo", models.IntegerField(db_column="presupuestoFondo")),
            ],
            options={
                "db_table": "vicerrectoriainvestigacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Integrantecomite",
            fields=[
                (
                    "idcomite",
                    models.OneToOneField(
                        db_column="idComite",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="investigacionApp.comite",
                    ),
                ),
                ("rol", models.CharField(blank=True, max_length=45, null=True)),
                ("fechadeingreso", models.DateField(db_column="fechaDeIngreso")),
            ],
            options={
                "db_table": "integrantecomite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Integrantegrupo",
            fields=[
                (
                    "idgrupoinvestigacion",
                    models.OneToOneField(
                        db_column="idGrupoInvestigacion",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="investigacionApp.grupoinvestigacion",
                    ),
                ),
                ("fechaingreso", models.DateField(db_column="fechaIngreso")),
                ("rol", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "integrantegrupo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Integranteproyecto",
            fields=[
                (
                    "idproyecto",
                    models.OneToOneField(
                        db_column="idProyecto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="investigacionApp.proyecto",
                    ),
                ),
                ("fechaingreso", models.DateField(db_column="fechaIngreso")),
                ("rol", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "integranteproyecto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Integrantepublicacion",
            fields=[
                (
                    "idpersona",
                    models.OneToOneField(
                        db_column="idPersona",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="investigacionApp.persona",
                    ),
                ),
                ("rol", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "integrantepublicacion",
                "managed": False,
            },
        ),
    ]
